superuser: null
# commented until <walletAmount> gets a class getter
welcomeMessage:
   <bold><yellow>Welcome to CryptoPlugin, the server that runs on Bitcoin! ^_^<reset>

   <yellow>Your CryptoPlugin address is <green><walletAddress>
   <yellow>Your balance is <green><walletAmount> SAT