api-version: 1.16
name: CryptoPlugin
version: 1.0
author: The CryptoPlugin Dev Team
main: com.cryptoplugin.cryptoplugin.CryptoPlugin
description: The CryptoPlugin Open Source Project
commands:
  emergencystop:
    description: "Stops the server cleanly in case of emergency"
    usage: "/emergencystop [reason]"
  wallet:
    description: "Displays your CryptoPlugin wallet info"
    usage: "/wallet"
  wallets:
    description: "Displays ALL your CryptoPlugin wallets info"
    usage: "/wallets"
  tip:
    description: "Tip is used for player to player transactions"
    usage: "/tip <amount> <playername>"
  withdraw:
    description: "withdraw is used for External transactions to an address"
    usage: "/withdraw <amount> <address>"
  backupkey:
    description: "used to back up your private key - DO NOT USE WHILE STREAMING OR IN VIEW OF ANYONE YOU WOULDNT WANT TO SEE."
    usage: "/backupkey <true>"
  crashtest:
    description: "Crashes the plugin on purpose, hell breaks loose. Don't try this at home"
    usage: "/crashtest"
